spring.application.name=simple-hris

# === SERVER ===
server.port=9002
server.address=0.0.0.0

# === DATASOURCE  ===
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# === HIKARI (BIAR TIDAK CRASH SAAT DB TELAT READY) ===
spring.datasource.hikari.initialization-fail-timeout=0
